import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class DomesticFlight extends JFrame {
    JComboBox CBFrom;
    JComboBox CBTo;
    JComboBox CBClass;
    JComboBox CBClient;
    JLabel LFrom;
    JLabel LTo;
    JLabel LBookingDate;
    JLabel LClass;
    JLabel LAdult;
    JLabel LBookingDetails;
    JLabel LPassengerDetails;
    JLabel LDate;
    JLabel LImg1;
    JLabel LNotes;
    JTextField TFBookingDate;
    Icon img1;
    JButton BFindFlight;
    JPanel PPanel1;
    JPanel PPanel2;
    StartPage type1;

    public DomesticFlight() {
        Container c = this.getContentPane();
        c.setLayout(new BorderLayout());
        String[] sItem1 = new String[]{"Bucharest"};
        String[] sItem2 = new String[]{"Targu-Mures", "Brasov ", "Constanta", "Timisoara", "Cluj-Napoca", "Iasi", "Craiova", "Tulcea", "Oradea"};
        String[] sItem3 = new String[]{"Economic", "Business"};
        this.type1 = this.type1;
        this.PPanel1 = new JPanel((LayoutManager)null);
        this.PPanel1.setPreferredSize(new Dimension(500, 200));
        this.LBookingDetails = new JLabel("<html><b><font color=\"#C71585\">Booking Details</font></b></html>");
        this.LFrom = new JLabel("Departure          :");
        this.LTo = new JLabel("Destination               :");
        this.LBookingDate = new JLabel("Booking Date:");
        this.LClass = new JLabel("Class         :");
        this.CBFrom = new JComboBox(sItem1);
        this.CBTo = new JComboBox(sItem2);
        this.CBClass = new JComboBox(sItem3);
        this.TFBookingDate = new JTextField(10);
        this.LDate = new JLabel("(DD/MM/YYYY)");
        this.LDate.setForeground(Color.yellow);
        this.img1 = new ImageIcon("C:\\Users\\Dobran\\4DeDa\\out\\production\\4DeDa\\Romania.png");
        this.LImg1 = new JLabel(this.img1);
        this.BFindFlight = new JButton("Find Flight");
        this.LBookingDetails.setBounds(20, 3, 100, 20);
        this.LFrom.setBounds(20, 40, 100, 20);
        this.CBFrom.setBounds(100, 40, 100, 20);
        this.LTo.setBounds(20, 100, 100, 20);
        this.CBTo.setBounds(100, 100, 100, 20);
        this.LBookingDate.setBounds(14, 160, 100, 20);
        this.TFBookingDate.setBounds(100, 160, 100, 20);
        this.LDate.setBounds(210, 160, 100, 20);
        this.LClass.setBounds(20, 220, 100, 20);
        this.CBClass.setBounds(100, 220, 100, 20);
        this.BFindFlight.setBounds(50, 270, 100, 25);
        this.LImg1.setBounds(-55, 290, 495, 260);
        this.PPanel1.add(this.LBookingDetails);
        this.PPanel1.add(this.LFrom);
        this.PPanel1.add(this.CBFrom);
        this.PPanel1.add(this.LTo);
        this.PPanel1.add(this.CBTo);
        this.PPanel1.add(this.LBookingDate);
        this.PPanel1.add(this.TFBookingDate);
        this.PPanel1.add(this.LDate);
        this.PPanel1.add(this.LClass);
        this.PPanel1.add(this.CBClass);
        this.PPanel1.add(this.BFindFlight);
        this.PPanel1.add(this.LImg1);
        this.PPanel1.setBackground(Color.white);
        c.add(this.PPanel1, "West");
        this.PPanel2 = new JPanel((LayoutManager)null);
        this.PPanel2.setPreferredSize(new Dimension(320, 160));
        this.LPassengerDetails = new JLabel("<html><b><font color=\"#C71585\">PassengerDetails</font></b></html>");
        this.LAdult = new JLabel("Client(12+)");
        String[] item4 = new String[]{"1", "2", "3", "4", "5", "6"};
        this.CBClient = new JComboBox(item4);
        this.LNotes = new JLabel("<html><body><p>NOTE: Bookings with International Credit Cards <p> have temporarily been suspended.This Service<p> will resume shortly and we will have a notice<p> posted on our website.We regret any <p>inconvenience caused to our passengers.</body></html>");
        this.LPassengerDetails.setBounds(40, 3, 100, 20);
        this.LAdult.setBounds(40, 40, 100, 20);
        this.CBClient.setBounds(140, 40, 100, 20);
        this.LNotes.setBounds(55, 240, 380, 180);
        this.PPanel2.add(this.LPassengerDetails);
        this.PPanel2.add(this.LAdult);
        this.PPanel2.add(this.CBClient);
        this.PPanel2.add(this.LNotes);
        this.PPanel2.setBackground(Color.white);
        c.add(this.PPanel2, "East");
        this.setSize(795, 580);
        this.setVisible(true);
        this.BFindFlight.addActionListener(new Button3(this, this.type1));
    }

    public static void main(String[] args) {
        StartPage type1 = null;
        new DomesticFlight();
    }
}
