import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class InternationalFlight extends JFrame {
    JComboBox CBFrom;
    JComboBox CBTo;
    JComboBox CBClass;
    JComboBox CBAdult;
    JComboBox CBChildren;
    JComboBox CBInfant;
    JLabel LFrom;
    JLabel LTo;
    JLabel LBookingDate;
    JLabel LClass;
    JLabel LAdult;
    JLabel LChildren;
    JLabel LInfant;
    JLabel LBookingDetails;
    JLabel LPassengerDetails;
    JLabel LDate;
    JLabel LImg1;
    JLabel LImg2;
    JLabel LNotes;
    JTextField TFBookingDate;
    Icon img1;
    Icon img2;
    JButton BFindFlight;
    JPanel PPanel1;
    JPanel PPanel2;
    StartPage type1;

    public InternationalFlight(StartPage type1) {
        Container c = this.getContentPane();
        c.setLayout(new BorderLayout());
        String[] sItem1 = new String[]{"Trivandrum"};
        String[] sItem2 = new String[]{"Bali", "Bangkok", "Cairo", "CapeTown", "Chicago", "Dubai", "Frankfurt", "HongKong", "Istanbul", "London", "LosAngeles", "Melbourne", "New York", "Paris", "Rome", "SanFrancisco", "shanghai", "Singapore", "Sydney", "Toronto"};
        String[] sItem3 = new String[]{"Economic", "Business"};
        this.type1 = type1;
        this.PPanel1 = new JPanel((LayoutManager)null);
        this.PPanel1.setPreferredSize(new Dimension(500, 200));
        this.LBookingDetails = new JLabel("<html><b><font color=\"#C71585\">Booking Details</font></b></html>");
        this.LFrom = new JLabel("From          :");
        this.LTo = new JLabel("To               :");
        this.LBookingDate = new JLabel("Booking Date:");
        this.LClass = new JLabel("Class         :");
        this.CBFrom = new JComboBox(sItem1);
        this.CBTo = new JComboBox(sItem2);
        this.CBClass = new JComboBox(sItem3);
        this.TFBookingDate = new JTextField(10);
        this.LDate = new JLabel("(DD/MM/YYYY)");
        this.LDate.setForeground(Color.red);
        this.img1 = new ImageIcon("C:\\Users\\Dobran\\untitled\\out\\production\\untitled\\Lumea.jpg");
        this.LImg1 = new JLabel(this.img1);
        this.BFindFlight = new JButton("Find Flight");
        this.LBookingDetails.setBounds(20, 3, 100, 20);
        this.LFrom.setBounds(20, 40, 100, 20);
        this.CBFrom.setBounds(100, 40, 100, 20);
        this.LTo.setBounds(20, 100, 100, 20);
        this.CBTo.setBounds(100, 100, 100, 20);
        this.LBookingDate.setBounds(14, 160, 100, 20);
        this.TFBookingDate.setBounds(100, 160, 100, 20);
        this.LDate.setBounds(210, 160, 100, 20);
        this.LClass.setBounds(20, 220, 100, 20);
        this.CBClass.setBounds(100, 220, 100, 20);
        this.BFindFlight.setBounds(50, 270, 100, 25);
        this.LImg1.setBounds(-100, 290, 595, 290);
        this.PPanel1.add(this.LBookingDetails);
        this.PPanel1.add(this.LFrom);
        this.PPanel1.add(this.CBFrom);
        this.PPanel1.add(this.LTo);
        this.PPanel1.add(this.CBTo);
        this.PPanel1.add(this.LBookingDate);
        this.PPanel1.add(this.TFBookingDate);
        this.PPanel1.add(this.LDate);
        this.PPanel1.add(this.LClass);
        this.PPanel1.add(this.CBClass);
        this.PPanel1.add(this.BFindFlight);
        this.PPanel1.add(this.LImg1);
        this.PPanel1.setBackground(Color.white);
        c.add(this.PPanel1, "West");
        this.PPanel2 = new JPanel((LayoutManager)null);
        this.PPanel2.setPreferredSize(new Dimension(320, 160));
        this.LPassengerDetails = new JLabel("<html><b><font color=\"#C71585\">PassengerDetails</font></b></html>");
        this.LAdult = new JLabel("Adults(12+)");
        this.LChildren = new JLabel("Children(2-11)");
        this.LInfant = new JLabel("Infants(under 2)");
        String[] item4 = new String[]{"1", "2", "3", "4", "5", "6"};
        this.CBAdult = new JComboBox(item4);
        String[] item5 = new String[]{"0", "1", "2", "3", "4"};
        this.CBChildren = new JComboBox(item5);
        String[] item6 = new String[]{"0", "1", "2", "3"};
        this.CBInfant = new JComboBox(item6);
        this.img2 = new ImageIcon("note_bg.gif");
        this.LImg2 = new JLabel(this.img2);
        this.LNotes = new JLabel("<html><body><p>NOTE: Bookings with International Credit Cards <p> have temporarily been suspended.This Service<p> will resume shortly and we will have a notice<p> posted on our website.We regret any <p>inconvenience caused to our passengers.</body></html>");
        this.LPassengerDetails.setBounds(40, 3, 100, 20);
        this.LAdult.setBounds(40, 40, 100, 20);
        this.CBAdult.setBounds(140, 40, 100, 20);
        this.LChildren.setBounds(40, 105, 100, 20);
        this.CBChildren.setBounds(140, 105, 100, 20);
        this.LInfant.setBounds(40, 170, 100, 20);
        this.CBInfant.setBounds(140, 170, 100, 20);
        this.LImg2.setBounds(16, 220, 320, 200);
        this.LNotes.setBounds(55, 240, 380, 180);
        this.PPanel2.add(this.LPassengerDetails);
        this.PPanel2.add(this.LAdult);
        this.PPanel2.add(this.LChildren);
        this.PPanel2.add(this.LInfant);
        this.PPanel2.add(this.CBAdult);
        this.PPanel2.add(this.CBChildren);
        this.PPanel2.add(this.CBInfant);
        this.PPanel2.add(this.LNotes);
        this.PPanel2.add(this.LImg2);
        this.PPanel2.setBackground(Color.white);
        c.add(this.PPanel2, "East");
        this.setSize(795, 580);
        this.setVisible(true);
        this.BFindFlight.addActionListener(new Button2(this, type1));
    }

    public static void main(String[] args) {
        StartPage type1 = null;
        new InternationalFlight((StartPage)type1);
    }
}
